In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
df = sns.load_dataset("iris")

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [15]:
df.rename(columns={'sepal_length':'sl','sepal_width':'sw','petal_length':'pl','petal_width':'pw'},inplace=True)
df.sample(5)

      sl   sw   pl   pw     species
1    4.9  3.0  1.4  0.2      setosa
140  6.7  3.1  5.6  2.4   virginica
108  6.7  2.5  5.8  1.8   virginica
86   6.7  3.1  4.7  1.5  versicolor
11   4.8  3.4  1.6  0.2      setosa

In [30]:
df.species.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [16]:
setosa = df[df['species']=='setosa']
versicolor = df[df['species']=='versicolor']
virginica = df[df['species']=='virginica']

In [19]:
print(setosa.shape)
print(versicolor.shape)
print(virginica.shape)

(50, 5)
(50, 5)
(50, 5)

In [23]:
print(setosa['sl'].mean())
print(setosa['sw'].mean())
print(setosa['pl'].mean())
print(setosa['pw'].mean())

5.006
3.428
1.4620000000000002
0.24599999999999997

In [27]:
print(setosa['sl'].median())
print(setosa['sw'].median())
print(setosa['pl'].median())
print(setosa['pw'].median())

5.0
3.4
1.5
0.2

In [31]:
print(stats.mode(setosa['sl']))
print(stats.mode(setosa['sw']))
print(stats.mode(setosa['pl']))
print(stats.mode(setosa['pw']))

ModeResult(mode=np.float64(5.0), count=np.int64(8))
ModeResult(mode=np.float64(3.4), count=np.int64(9))
ModeResult(mode=np.float64(1.4), count=np.int64(13))
ModeResult(mode=np.float64(0.2), count=np.int64(29))

In [24]:
print(virginica['sl'].mean())
print(virginica['sw'].mean())
print(virginica['pl'].mean())
print(virginica['pw'].mean())

6.587999999999998
2.974
5.5520000000000005
2.0260000000000002

In [28]:
print(virginica['pw'].median())
print(virginica['sl'].median())
print(virginica['sw'].median())
print(virginica['pl'].median())

2.0
6.5
3.0
5.55

In [32]:
print(stats.mode(virginica['sl']))
print(stats.mode(virginica['sw']))
print(stats.mode(virginica['pl']))
print(stats.mode(virginica['pw']))

ModeResult(mode=np.float64(6.3), count=np.int64(6))
ModeResult(mode=np.float64(3.0), count=np.int64(12))
ModeResult(mode=np.float64(5.1), count=np.int64(7))
ModeResult(mode=np.float64(1.8), count=np.int64(11))

In [26]:
print(versicolor['sl'].mean())
print(versicolor['sw'].mean())
print(versicolor['pl'].mean())
print(versicolor['pw'].mean())

5.936
2.7700000000000005
4.26
1.3259999999999998

In [29]:
print(versicolor['sl'].median())
print(versicolor['sw'].median())
print(versicolor['pl'].median())
print(versicolor['pw'].median())

5.9
2.8
4.35
1.3

In [33]:
print(stats.mode(versicolor['sl']))
print(stats.mode(versicolor['sw']))
print(stats.mode(versicolor['pl']))
print(stats.mode(versicolor['pw']))

ModeResult(mode=np.float64(5.5), count=np.int64(5))
ModeResult(mode=np.float64(3.0), count=np.int64(8))
ModeResult(mode=np.float64(4.5), count=np.int64(7))
ModeResult(mode=np.float64(1.3), count=np.int64(13))